// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5jByAXUHj_3u-Znt9zzxn_YPe5mZ2gGE',
    appId: '1:378334067029:web:3ad96f6dd9b0b85cb657dc',
    messagingSenderId: '378334067029',
    projectId: 'bus-management-system-1a375',
    authDomain: 'bus-management-system-1a375.firebaseapp.com',
    storageBucket: 'bus-management-system-1a375.firebasestorage.app',
    measurementId: 'G-QEVTBVHSSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeoWWdmVSzsqLTjOGIJadBaIskFOHd3Q8',
    appId: '1:378334067029:android:8c9a8e1fcc320c57b657dc',
    messagingSenderId: '378334067029',
    projectId: 'bus-management-system-1a375',
    storageBucket: 'bus-management-system-1a375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWEn_VKbmdNEHgBIBqBYlw-Cp4nP13E0',
    appId: '1:378334067029:ios:f53b403412ef96c6b657dc',
    messagingSenderId: '378334067029',
    projectId: 'bus-management-system-1a375',
    storageBucket: 'bus-management-system-1a375.firebasestorage.app',
    iosBundleId: 'com.example.busManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWEn_VKbmdNEHgBIBqBYlw-Cp4nP13E0',
    appId: '1:378334067029:ios:f53b403412ef96c6b657dc',
    messagingSenderId: '378334067029',
    projectId: 'bus-management-system-1a375',
    storageBucket: 'bus-management-system-1a375.firebasestorage.app',
    iosBundleId: 'com.example.busManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5jByAXUHj_3u-Znt9zzxn_YPe5mZ2gGE',
    appId: '1:378334067029:web:e5e6dcaa9ac9a0b1b657dc',
    messagingSenderId: '378334067029',
    projectId: 'bus-management-system-1a375',
    authDomain: 'bus-management-system-1a375.firebaseapp.com',
    storageBucket: 'bus-management-system-1a375.firebasestorage.app',
    measurementId: 'G-RBNMYK6LFZ',
  );

}